public class Player {
    public void playing() {
        String player1name = 'John';
        system.debug(player1name);
        Integer player1namelength = player1name.length();
        system.debug(player1namelength);
        string upperPlayer1Name = player1name.toUpperCase();
        system.debug(upperPlayer1Name);


        String player2Name = 'Amy';
        system.debug(player2name);
        Integer player2namelength = player1name.length();
        system.debug(player2namelength);


        string player3Name = 'John';
        system.debug(player3name);
        Integer player3namelength = player1name.length();
        system.debug(player3namelength);
        string upperPlayer3Name = player3name.toUpperCase();
        system.debug(upperPlayer3Name);

        string player4Name = 'Mary';
        system.debug(player4Name);
        Integer player4namelength = player1name.length();
        system.debug(player4namelength);

        String player5name = 'William';
        system.debug(player5name);
        Integer player5namelength = player1name.length();
        system.debug(player5namelength);

    }
}