OperatiponHelper o1 =new OperatiponHelper();
o1.largestOutofTwoNumbers(3, 4);
system.debug(o1.smallestOutofTwoNumbers(3, 4, 1));
system.debug(o1.sumofPositiveIntegers(-8));

List<Decimal> value=new List<Decimal>{
     12 , 13.5 ,19.9
};
system.debug(OperatiponHelper.sumList(value));
system.debug(OperatiponHelper.avarageList(value));
system.debug(OperatiponHelper.highestList(value));
system.debug(OperatiponHelper.Lowest(value));